before_install:
- npm install -g grunt-cli
language: node_js
node_js:
- '0.10'
notifications:
  email: false
  slack:
    secure: cJ518m8KUBa9axVO68q4DJxwCFa+aKVL/CchrJT9Xh1V7wr3GkUuDxdR0xQltRvNzWcwSVCwbXmGAXb25QR10Jt800uN3ti0FNpxVpyu4aMxhdN3o7CWPVeBs1nkoyenogX0tFiK0VjIlid7R9271e+WBn7CbSiXktJnMpNcyGg=
env:
  global:
  - secure: LFNvylJRQSDKul6345ONSdPXlpersxAX28GTo8z+Z7/lmvYV4H7PBbNHDsc77ZE4TuFJZ5rvOJ9jx/iE+mveUAs4GpeQ6q+Qy/bcFUYqtCWZa2/L8D2lPSrgGqkG2Vnp8btMHK8eR3MbTeJn0FF+1vQEZEfJusGTcST5ULTeFzo=
deploy:
  provider: npm
  email: stephan@thehoodiefirm.com
  on:
    all_branches: true
    tags: true
  api_key:
    secure: dcqm/XHVMmB66DZoRy6yKec3x8MKmlxIULZMii84t+la7J31JkRchrFFuqcNprKnvaGOw3nRZDWJcqqYvrJ917WrDujJHLJkFjIFf4ynrk4KqSkE6bhv3gdxkNG1EJ/92/ZLSQL4ZzLijmYg4jPcgg13GrvcAco6w9s0C30zJkU=
before_deploy:
- grunt before-deploy
after_deploy:
- grunt after-deploy
sudo: false
cache:
  directories:
  - node_modules
