before_install:
- npm install -g grunt-cli
after_success:
- grunt ghrelease
language: node_js
node_js:
- '0.10'
notifications:
  email: false
env:
  global:
    secure: gWPb0vAvaZMawGS9LpAIF3EVdBZptTtfnUaH8IKVMa11gJ3bmajQv0PhMtHTiuHNZ13RNE5Js1edmNc6PgV9hJc0sFRZmXALshf3ym9E/YMeE+h4ZuXDmtQN5YpnDzRiSQgYvMt6DL5764EGfkQfGZqt3uJj/p7LtDEmVxb3KPw=
deploy:
  provider: npm
  email: stephan@thehoodiefirm.com
  api_key:
    secure: Wnr8DgqzLLK4tIM2koDx69EUqTmHNa5ksQsEP9lbL6BvytO4u4yyXDh5CCtVBS3dpZH4gpsH3wQIm8x1SbGoMFw47OZ3QfarOzq+V8p8Rhknjh7Zg3Vux52rWqOM9v/rZgKSAsnPmP2BoYxaXQACnbZlQV17rIh4Gf31G8WHBsc=
  on:
    all_branches: true
    tags: true
